delete from army_lists where legacy = true;
insert into army_lists (id, name, abbrev, alignment, legacy, keywords, inserted_at, updated_at) values
(  0, 'Angmar',                'n_angmar',        1, true, '',                CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(  9, 'Dead of Dunharrow',     'n_dunharrow',     0, true, 'miscGood',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 10, 'Easterlings',           'n_easterlings',   0, true, 'mordorAndAllies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 13, 'Corsairs of Umbar',     'n_corsairs',      1, true, 'mordorAndAllies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 15, 'Fiefdoms',              'n_fiefdoms',      0, true, 'gondor',          CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 20, 'Khand',                 'n_khand',         1, true, 'mordorAndAllies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 21, 'Khazad-dûm',            'n_khazad_dum',    0, true, 'dwarves',         CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 25, 'Dol Guldur',            'n_dol_guldur',    1, true, '',                CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 26, 'Eagles',                'n_eagles',        0, true, 'miscGood',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 33, 'Sharkey''s Rogues',     'n_rogues',        1, true, 'miscEvil',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 41, 'Wanderers in the Wild', 'n_wanderers',     0, true, 'miscGood',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 43, 'Woses',                 'n_wildmen',       0, true, 'miscGood',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 44, 'Beornings',             'n_beornings',     0, true, 'menOfTheNorth',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 87, 'Arnor',                 'n_arnor',         0, true, 'menOfTheNorth',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 88, 'Dale',                  'n_dale',          0, true, 'menOfTheNorth',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 89, 'Dunland',               'n_dunland',       1, true, 'isengard',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 90, 'Erebor',                'n_erebor',        0, true, 'dwarves',         CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 91, 'Fangorn',               'n_fangorn',       0, true, 'miscGood',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 92, 'Fellowship',            'n_fellowship',    0, true, 'hobbits',         CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 93, 'Goblin-town',           'n_goblintown',    1, true, 'miscEvil',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 94, 'Gondor',                'n_gondor',        0, true, 'gondor',          CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 95, 'Gundabad',              'n_gundabad',      1, true, '',                CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 96, 'Harad',                 'n_harad',         1, true, 'mordorAndAllies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 97, 'Isengard',              'n_isengard',      1, true, 'isengard',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 98, 'Lake-town',             'n_laketown',      0, true, 'menOfTheNorth',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
( 99, 'Lothlórien',            'n_lothlorien',    0, true, 'elves',           CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100, 'Mordor',                'n_mordor',        1, true, 'mordorAndAllies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(101, 'Moria',                 'n_moria',         1, true, '',                CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 'Rivendell',             'n_rivendell',     0, true, 'elves',           CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(103, 'Rohan',                 'n_rohan',         0, true, '',                CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(104, 'Shire',                 'n_shire',         0, true, 'hobbits',         CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(105, 'Thorin''s Company',     'n_thorins_co',    0, true, 'dwarves',         CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(106, 'Thranduil''s Realm',    'n_thranduil',     0, true, 'elves',           CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(107, 'White Council',         'n_white_council', 0, true, 'miscGood',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(108, 'Númenor',               'n_numenor',       0, true, 'miscGood',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(109, 'Iron Hills',            'n_iron_hills',    0, true, 'dwarves',         CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(110, 'Trolls',                'n_trolls',        1, true, 'miscEvil',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(111, 'Rohan Traitors',        'n_traitors',      1, true, 'miscEvil',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
;
