/* Initial population of books table. */
delete from books;
insert into books (id, key, short_name, year, name, inserted_at, updated_at) values
(0, 'bot5a',   'Bo5A',    '2014', 'Battle of the Five Armies', current_timestamp, current_timestamp),
(1, 'bpf',     'BoPF',    '2004', 'Battle of the Pelennor Fields', current_timestamp, current_timestamp),
(2, 'dos',     'DoS',     '2013', 'Desolation of Smaug', current_timestamp, current_timestamp),
(3, 'fotn',    'FotN',    '2006', 'Fall of the Necromancer', current_timestamp, current_timestamp),
(4, 'fotr',    'FotR',    '2001', 'Fellowship of the Ring', current_timestamp, current_timestamp),
(5, 'fotr_jb', 'FotR',    '2005', 'Fellowship of the Ring', current_timestamp, current_timestamp),
(6, 'fp',      'FP',      '2011', 'Free Peoples', current_timestamp, current_timestamp),
(7, 'fr',      'FR',      '2011', 'Fallen Realms', current_timestamp, current_timestamp),
(8, 'gif',     'GiF',     '2007', 'Gondor in Flames', current_timestamp, current_timestamp),
(9, 'gt',      'EfG',    '2012', 'Escape from Goblintown', current_timestamp, current_timestamp),
(10, 'harad',   'Harad',  '2007', 'Harad', current_timestamp, current_timestamp),
(11, 'hobbit',  'HUJ',    '2012', 'The Hobbit: An Unexpected Journey', current_timestamp, current_timestamp),
(12, 'kd',      'KD',     '2007', 'Khazad-dûm', current_timestamp, current_timestamp),
(13, 'km',      'KoM',    '2011', 'Kingdoms of Men', current_timestamp, current_timestamp),
(14, 'ma',      'M&A',    '2011', 'Moria & Angmar', current_timestamp, current_timestamp),
(15, 'mordor',  'Mordor', '2011', 'Mordor', current_timestamp, current_timestamp),
(16, 'omordor', 'Mordor', '2007', 'Mordor', current_timestamp, current_timestamp),
(17, 'roa',     'Arnor',  '2006', 'Ruin of Arnor', current_timestamp, current_timestamp),
(18, 'rotk',    'RotK',   '2003', 'Return of the King', current_timestamp, current_timestamp),
(19, 'rotk_jb', 'RotK',   '2007', 'Return of the King', current_timestamp, current_timestamp),
(20, 'saf',     'S&F',    '2003', 'Shadow & Flame', current_timestamp, current_timestamp),
(21, 'sbg',     'SBG Magazine', '',  'SBG Magazine', current_timestamp, current_timestamp),
(22, 'site',    'SitE',   '2005', 'A Shadow in the East', current_timestamp, current_timestamp),
(23, 'sog',     'SoG',    '2004', 'Siege of Gondor', current_timestamp, current_timestamp),
(24, 'sots',    'SotS',   '2004', 'The Scouring of the Shire', current_timestamp, current_timestamp),
(25, 'tba',     'T&BA',   '2016', 'There and Back Again', current_timestamp, current_timestamp),
(26, 'ttt',     'TTT',    '2002', 'The Two Towers', current_timestamp, current_timestamp),
(27, 'ttt_jb',  'TTT',    '2006', 'The Two Towers', current_timestamp, current_timestamp),
(28, 'bpf_ss',  'BoPF',   '2018', 'Battle of the Pelennor Fields', current_timestamp, current_timestamp),
(29, 'alotr',   'ALotR',  '2018', 'Armies of the Lord of the Rings', current_timestamp, current_timestamp),
(30, 'ah',      'AH',     '2018', 'Armies of the Hobbit', current_timestamp, current_timestamp),
(31, 'gaw',     'GaW',    '2019', 'Gondor at War', current_timestamp, current_timestamp),
(32, 'bgime',   'BGiME',  '2002-', 'Battle Games in Middle Earth', current_timestamp, current_timestamp),
(33, 'sos2',    'SotS',   '2019', 'The Scouring of the Shire', current_timestamp, current_timestamp),
(34, 'wfr',     'WiR',    '2019', 'War in Rohan', current_timestamp, current_timestamp),
(35, 'qrb',     'Quest',  '2020', 'Quest of the Ringbearer', current_timestamp, current_timestamp),
(36, 'fotn2',   'FotN',    '2021', 'Fall of the Necromancer', current_timestamp, current_timestamp),
(37, 'dotn',    'DotN',   '2022', 'Defence of the North', current_timestamp, current_timestamp),
(38, 'bog',     'BoO',    '2022', 'Battle of Osgiliath', current_timestamp, current_timestamp),
(39, 'ang',     'Angmar', '2024', 'Rise of Angmar', current_timestamp, current_timestamp),
(40, 'alotr2',  'ALotR',  '2024', 'Armies of the Lord of the Rings', current_timestamp, current_timestamp),
(41, 'ah2',     'AH',     '2024', 'Armies of the Hobbit', current_timestamp, current_timestamp),
(42, 'aaa',     'AoA&A',  '2024', 'Armies of Arnor and Angmar', current_timestamp, current_timestamp),
(43, 'twotr',   'tWotR',  '2024', 'The War of the Rohirrim', current_timestamp, current_timestamp)
